sudo: required

language: node_js

node_js:
- lts/*

services:
- docker

install:
- npm install

script:
- npm run lint
- npm run build
- npm run test

deploy:
  skip_cleanup: true
  provider: script
  script: >-
    docker build -t libero/editor . &&
    docker tag libero/editor libero/editor:${TRAVIS_TAG#?} &&
    IMAGE_TAG=${TRAVIS_TAG#?} scripts/travis/push-image.sh editor
  on:
    branch: master
    tags: true